server.port=24301

base.url.email=http://localhost:8082/api/email/sendMail
base.url.verification.email=http://localhost:8082/api/email/sendEmailMail

jwt.secret: ================Acknowldeged=SpringSecretKey================
# jwt.expirationDateInMs: 18000000
# jwt.expirationDateInMs=86400000 24 hours

# 6 Months
jwt.expirationDateInMs=15770000000


# Database properties for MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/3POL_DB_MASTER
spring.datasource.username=root
spring.datasource.password=StrongPassword123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.main.allow-circular-references=true

